import type { Metadata } from 'next';
import './globals.css';
import { jost } from './ui/font';

export const metadata: Metadata = {
    title: 'GumiShopify',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${jost.className} antialiased`}>{children}</body>
        </html>
    );
}
